// Generated by LiveScript 1.4.0
(function(){
  var Disc, Modele, mettrePion;
  Disc = (function(){
    Disc.displayName = 'Disc';
    var prototype = Disc.prototype, constructor = Disc;
    function Disc(pos){
      this.pos = pos;
      this.initColorNumber = Modele.grille[this.pos];
    }
    prototype.goToDir = function(dir){
      var newPos, pos;
      newPos = this.pos;
      for (;;) {
        pos = newPos;
        newPos = pos + dir;
        if (!(this.distance(pos, newPos) <= 1 && Modele.grille[newPos] == this.initColorNumber)) {
          break;
        }
      }
      return pos;
    };
    prototype.distance = function(disc1, disc2, xOrY){
      var x$, y$, distY, z$, ref$, ref1$;
      x$ = Math;
      y$ = x$.floor;
      distY = y$(disc2 / 7) - y$(disc1 / 7);
      z$ = x$.abs;
      return (ref$ = z$(disc2 % 7 - disc1 % 7)) > (ref1$ = z$(distY)) ? ref$ : ref1$;
      return x$;
    };
    prototype.getLoopIf4InARow = function(dir){};
    return Disc;
  }());
  window.Modele = Modele = {
    isGameFinish: function(){
      var isGameFinish;
      return this.isGameFinish = function(pos){
        var disc;
        if (pos < 0) {
          return false;
        }
        if (pos != null) {
          if (typeof pos === 'boolean') {
            isGameFinish = pos;
          } else {
            disc = new Disc(pos);
            [1, 6, 7, 8].some(function(dir){
              var x$, res$, i$, to$, i, isGameFinish;
              x$ = bind$(disc, 'goToDir');
              res$ = [];
              for (i$ = x$(-dir), to$ = x$(dir); dir < 0 ? i$ >= to$ : i$ <= to$; i$ += dir) {
                i = i$;
                res$.push(i);
              }
              Modele.winningPos = res$;
              return isGameFinish = Modele.winningPos.length > 3;
            });
          }
        }
        return isGameFinish;
      };
    },
    play: function(position, test){
      position %= 7;
      while (Modele.grille[position + 7] == 0 && position < 37) {
        position += 7;
      }
      if (Modele.grille[position] == 0) {
        Modele.mettrePion(position, test);
        return position;
      }
      return -1;
    },
    mettrePion: mettrePion = function(position, test){
      Modele.grille[position] = Modele.getPlayer();
      if (!test) {
        Modele.nextPlayer();
        Modele.backup.push(position);
      }
      Modele.isGameFinish(position);
      if (test) {
        Modele.grille[position] = 0;
      }
      return Modele.isGameFinish();
    },
    playAgain: function(emplacement){
      Modele.isGameFinish(false);
      Modele.init();
      Modele.setPlayer(1);
      Modele.play(3);
      return Modele.backup = [38];
    },
    joueur: '1',
    grille: [],
    backup: [],
    init: function(){
      var i;
      i = 0;
      while (i < 42) {
        Modele.grille[i] = 0;
        i++;
      }
      return Modele.isGameFinish(false);
    },
    setGrille: function(tab){
      var i, results$ = [];
      i = 0;
      while (i < 42) {
        Modele.grille[i] = tab[i];
        results$.push(i++);
      }
      return results$;
    },
    setModel: function(tab){
      return Modele.setGrille(Modele.modelToArray(tab));
    },
    modelToArray: function(tab){
      var tab2, lengthLine, i, o;
      tab2 = [];
      lengthLine = tab[0].length;
      i = 0;
      while (i < tab.length) {
        o = 0;
        while (o < lengthLine) {
          tab2.push(tab[i][o]);
          o++;
        }
        i++;
      }
      return tab2;
    },
    loadTab: function(tab, emplacement){
      return Modele.grille = Modele.modelToArray(tab);
    },
    nextPlayer: function(){
      return Modele.joueur = Modele.joueur == 1 ? 2 : 1;
    },
    getPlayer: function(dec){
      var nb;
      nb = parseInt(Modele.joueur);
      if (dec == 1) {
        nb = nb % 2 + 1;
      }
      return nb;
    },
    setPlayer: function(number){
      return Modele.joueur = number;
    },
    isHumanTurn: function(){
      return Modele.joueur == 1;
    },
    undo: function(emplacement, Nothuman){
      var pos;
      Modele.isGameFinish(false);
      pos = Modele.backup.pop();
      if (pos == 38) {
        return Modele.backup.push(pos);
      }
      Modele.grille[pos] = 0;
      Modele.nextPlayer();
      return pos;
    },
    restore: function(backup){
      var joueur, i;
      Modele.partiFini = false;
      Modele.init();
      joueur = 1;
      Modele.backup = backup;
      i = backup.lastIndexOf(38);
      while (i < backup.length) {
        if (Modele.grille[backup[i]] == 0) {
          Modele.grille[backup[i]] = joueur;
          joueur = joueur % 2 + 1;
        }
        i++;
      }
      return Modele.setPlayer(Modele.backup % 2 + 1);
    },
    saveGame: function(){
      $.cookie('grille', JSON.stringify(Modele.backup));
      return $.cookie('boolSmart', JSON.stringify(IA.boolSmart));
    }
  };
  Modele.init();
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
}).call(this);
