// Generated by LiveScript 1.4.0
(function(){
  var state;
  state = (function(){
    switch (false) {
    case 2 + 2 !== 5:
      return 2;
    default:
      return 5;
    }
  }());
  state = 2 + 2 === 5 ? 2 : 5;
}).call(this);
