// Generated by LiveScript 1.4.0
(function(){
  window.app = angular.module('aa', []);
  window.app.controller('aa2', function($scope){
    var o;
    window.o = o = $scope;
    return o.test = 0;
  });
}).call(this);
