// Generated by LiveScript 1.4.0
(function(){
  window.borto.cookies = {
    set: function(key, val){
      return document.cookie = key + "=" + val + ";";
    },
    get: function(it){
      return RegExp(it + "=([^;]*);?").exec(document.cookie)[1];
    },
    getTab: function(it){
      return eval("[" + this.get(it) + "]");
    }
  };
}).call(this);
